name: Python package


on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        brew update && brew install gmp boost || echo ""
        python3 -m venv venv
        source venv/bin/activate
        pip install lib/py-setproctitle
        pip install .
    - name: Test proof of space
      run: |
        source venv/bin/activate
        pip wheel lib/chiapos
        lib/chiapos/build/RunTests
    - name: Test vdf
      run: |
        source venv/bin/activate
        pip wheel lib/chiavdf/fast_vdf
        cd lib/chiavdf/fast_vdf
        python python_bindings/test_verifier.py
        cd ../../../
    - name: Lint source with flake8
      run: |
        ./venv/bin/flake8 src
    - name: Lint source with mypy
      run: |
        ./venv/bin/mypy src tests
    - name: Test blockchain code with pytest
      run: |
        ./venv/bin/py.test tests -s -v

